# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project. 
          
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
          
      - name: Install Cygwin
        # You may pin to the exact commit or the version.
        # uses: egor-tensin/setup-cygwin@4f96f9fecb8c952fa32ff791b0a77d93d5191bb4
        uses: egor-tensin/setup-cygwin@v3
        with:
          # Target platform
          platform: x64 # optional, default is x64
          # Installation directory
          install-dir: C:\tools\cygwin  # optional, default is C:\tools\cygwin
          # Packages to install, separated by a space
          packages: wget zip pkg-config make cmake mingw64-i686-gcc-g++ mingw64-x86_64-gcc-g++ binutils nasm gettext-devel libglib2.0-devel openssl # optional
          # Value to set as the CYGWIN environment variable
          #env: # optional
          # Convert symlinks in /usr/bin to hardlinks
          #hardlinks: # optional, default is 0

      - name: Download File To Workspace
          # You may pin to the exact commit or the version.
          # uses: carlosperate/download-file-action@e85e0aa6262f13571d17a4a39687b26981c583dc
        uses: carlosperate/download-file-action@v1.0.3
        with:
            # URL of the file to download
            file-url: https://cygwin.com/setup-x86_64.exe
            # New filename to rename the downloaded file
            file-name: setup.exe # optional
            # Path to download the file
            location: C:\tools\cygwin # optional, default is .
 
      # Cygwin executables are added to PATH, so you can call them directly:
      - run: | 
          bash ./build.sh setup C:/tools/cygwin/setup.exe
          bash ./build.sh bdist
      
          
